name: Demo Release

on:
  push:
    tags:
      - "v*"

env:
  TZ: Asia/Shanghai

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Demo ${{ github.ref }}
          draft: false
          prerelease: false